before_build:
  - cmd: choco install wget
  - wget -q https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe
  - dotnet-1.1.1-sdk-win-x64.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

build_script:
  - cmd: cd NScrape
  - cmd: dotnet restore NScrape.Core.csproj
  - cmd: dotnet build NScrape.Core.csproj
  - cmd: dotnet pack NScrape.Core.csproj --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - ps: Push-AppveyorArtifact "bin\Debug\CoreCompat.NScrape.0.4.0-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"

test: off